import {FONTS,PALETTES} from './model.js';
import {activeLocale} from './localization.js';
import {isPhone3D,phoneSettings,PHONE_COLORS} from './phone-data.js';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const section=(title,body)=>`<section class="control-section"><div class="section-title"><h3>${title}</h3></div>${body}</section>`;
const field=(key,label,value,min,max,step=1)=>`<label class="field-label" for="prop-${key}">${label}</label><input id="prop-${key}" data-prop="${key}" type="number" value="${Number(value.toFixed(2))}" min="${min}" max="${max}" step="${step}">`;
const range=(key,label,value,min,max,step=1,suffix='')=>`<div class="range-label"><label for="prop-${key}">${label}</label><output data-output="${key}">${Number(value.toFixed(2))}${suffix}</output></div><input id="prop-${key}" data-prop="${key}" type="range" value="${value}" min="${min}" max="${max}" step="${step}" data-suffix="${suffix}">`;
const colors=items=>`<div class="color-fields">${items.map(([key,label,value])=>`<label><input type="color" data-prop="${key}" value="${value}" aria-label="${label}"><span>${label}</span></label>`).join('')}</div>`;
const check=(key,label,value)=>`<label class="checkbox-label"><input data-prop="${key}" type="checkbox" ${value?'checked':''}>${label}</label>`;
const select=(key,label,value,items)=>`<label class="field-label" for="prop-${key}">${label}</label><select id="prop-${key}" data-prop="${key}">${items.map(([v,t])=>`<option value="${esc(v)}" ${value===v?'selected':''}>${t}</option>`).join('')}</select>`;
export function inspectorHTML(frame,layer,project,options={}){
  if(layer?.type==='device')layer=phoneSettings(layer);
  const linkedSource=frame.sources?.[layer?.sourceSide??0],replaceAction=linkedSource?`replace-${layer?.sourceSide===1?'right':'left'}`:'replace';
  const source=`<button class="source-button" data-action="${replaceAction}"><span aria-hidden="true">▧</span><span><strong>${linkedSource?esc(linkedSource.name):frame.demo?'Загрузить свой экран':esc(frame.sourceName)}</strong><small>Заменить интерфейс</small></span></button>`;
  const exp=section('Экспорт',`<button class="button full" data-action="open-export">Настроить экспорт…</button><p class="small muted">Кадры, языки, оба размера и масштаб PNG — в одном окне.</p>`);
  if(frame.columns===2&&(!layer||options.viewOnly)){
    const sources=section('Экраны приложения',frame.sources.map((s,i)=>`<button class="source-button" data-action="replace-${i?'right':'left'}"><span aria-hidden="true">▧</span><span><strong>${i?'Правый':'Левый'} кадр</strong><small>${esc(s.name)}</small></span></button>`).join(''));
    if(options.viewOnly)return `<div class="inspector-heading"><h2>Часть панорамы</h2></div><p class="pano-help">Этот PNG — часть общего холста. Композиция редактируется сразу для двух кадров.</p><button class="button full" data-action="edit-panorama">Редактировать панораму</button><div style="margin-top:20px">${sources}${exp}</div>`;
    return `<div class="inspector-heading"><h2>Панорама · 2 кадра</h2></div>`+sources+
      section('Общий фон',`<div class="color-fields"><label><input id="background" type="color" value="${frame.background}"><span>Цвет</span></label></div><label class="checkbox-label"><input id="gradient" type="checkbox" ${frame.gradient?'checked':''}>Мягкий градиент через оба кадра</label>`)+
      section('Объекты на стыке',`<button class="button full" data-action="center-seam">Телефон на стыке</button><p class="pano-help">Любой слой можно перенести через центральную линию. Для X и ширины 100% равны одному кадру.</p><div class="action-row"><button class="button" data-action="add-phone">Телефон</button><button class="button" data-action="add-text">Текст</button><button class="button" data-action="add-graphic">Графика</button></div><button class="text-button" data-action="add-crop">Добавить вырезку UI</button>`)+exp+
      section('Раздельное оформление',`<p class="pano-help">Вернуть композиции, которые были до объединения. Правки общей панорамы заменятся исходным оформлением; действие можно отменить.</p><button class="button full" data-action="restore-separate">Вернуть исходное оформление</button>`);
  }
  if(!layer){
    return `<div class="inspector-heading"><h2>Оформление кадра</h2><span class="pill">${esc(activeLocale(project))}</span></div>`+
      section('Интерфейс приложения',source)+
      section('Композиция',`<div class="compositions">${[['hero','Крупный UI'],['tilt','Перспектива'],['focus','Акцент на UI']].map(([key,title])=>`<button class="composition ${key}" data-composition="${key}" aria-pressed="${frame.composition===key}"><span class="composition-icon" aria-hidden="true"></span>${title}</button>`).join('')}</div><p class="small muted" style="margin-top:10px">Тексты и твой экран сохраняются. Положение основных элементов изменится.</p>`)+
      section('Цвета',`<div class="palettes">${[['blue','Электрик'],['light','Светлая'],['dark','Графит']].map(([key,title])=>`<button class="palette ${key}" data-palette="${key}" aria-pressed="${frame.background===PALETTES[key].background}">${title}</button>`).join('')}</div><div class="color-fields"><label><input id="background" type="color" value="${frame.background}"><span>Фон</span></label></div><label class="checkbox-label"><input id="gradient" type="checkbox" ${frame.gradient?'checked':''}>Мягкий градиент</label><button class="text-button" style="margin-top:16px" data-action="apply-style">Цвета и шрифты всему комплекту</button>`)+
      section('Добавить',`<button class="button full" data-action="enable-3d">Настроить iPhone 17 в 3D</button><div class="action-row" style="margin-top:10px"><button class="button" data-action="add-text">Текст</button><button class="button" data-action="add-graphic">Графика</button><button class="button" data-action="add-crop">Вырезка UI</button></div><button class="text-button" data-action="layers" style="margin-top:16px">Открыть слои кадра</button>`)+exp;
  }
  const name=`<label class="field-label" for="prop-name">Название слоя</label><input id="prop-name" type="text" data-prop="name" value="${esc(layer.name)}" maxlength="100">`;
  let specific='';
  if(layer.type==='text'){
    specific=section('Текст',`<label class="sr-only" for="prop-text">Текст слоя</label><textarea id="prop-text" data-prop="text" rows="3" maxlength="1000">${esc(layer.text)}</textarea><div class="field-grid"><div>${select('fontFamily','Шрифт',layer.fontFamily,FONTS.map(f=>[f,f]))}</div><div>${select('fontWeight','Начертание',layer.fontWeight,[[400,'Обычное'],[600,'Полужирное'],[700,'Жирное'],[800,'Очень жирное'],[900,'Максимальное']])}</div></div>`+
      range('fontSize','Размер',layer.fontSize,10,110,1,' px')+range('lineHeight','Межстрочный',layer.lineHeight,.8,2,.05)+
      `<div class="segmented alignment" role="group" aria-label="Выравнивание текста">${[['left','Слева'],['center','Центр'],['right','Справа']].map(([key,label])=>`<button data-align="${key}" aria-pressed="${layer.align===key}">${label}</button>`).join('')}</div>`+
      colors([['color','Текст',layer.color]])+`<label class="field-label" for="prop-highlight">Выделить слово или фразу</label><input id="prop-highlight" type="text" data-prop="highlight" value="${esc(layer.highlight)}" maxlength="100" placeholder="Например, clearer">`+colors([['highlightColor','Акцент',layer.highlightColor]]));
  }else if(layer.type==='device'){
    const real=isPhone3D(layer),poses=project.savedPoses??[];
    const deviceSource=layer.image?`<button class="source-button" data-action="replace-device"><span aria-hidden="true">▧</span><span><strong>${esc(layer.sourceName)}</strong><small>Отдельный экран телефона</small></span></button><button class="text-button" data-action="use-frame-source">Использовать общий экран кадра</button>`:source+`<button class="text-button" data-action="replace-device">Назначить отдельный экран</button>`;
    specific=section('Модель телефона',select('deviceModel','Мокап',layer.deviceModel,[['iphone17','iPhone 17 · 3D'],['flat','Обычная рамка']]))+section('Интерфейс',deviceSource+(real?select('screenFit','Размещение экрана',layer.screenFit,[['contain','Вписать полностью'],['cover','Заполнить с обрезкой']])+range('screenZoom','Масштаб UI',layer.screenZoom,1,3,.05,'×')+range('screenX','Кадрирование по горизонтали',layer.screenX,0,100,1,'%')+range('screenY','Кадрирование по вертикали',layer.screenY,0,100,1,'%')+check('island','Показать Dynamic Island',layer.island)+`<p class="small muted">Отключи Dynamic Island, если вырез уже есть на твоём скриншоте.</p>`:''));
    specific+=section('Ракурс',`<div class="segmented" role="group" aria-label="Поза телефона"><button data-pose="front">Прямо</button><button data-pose="left">Влево</button><button data-pose="right">Вправо</button>${real?'<button data-pose="back">Сзади</button>':''}</div>`+
      range('yaw','Разворот',layer.yaw,real?-180:-40,real?180:40,1,'°')+range('pitch','Наклон в глубину',layer.pitch,real?-180:-30,real?180:30,1,'°')+(real?range('perspective','Перспектива',layer.perspective,15,60,1,'°')+`<p class="small muted">Кнопка «Вращать 3D» над холстом включает поворот мышью. Круглый маркер поворачивает в плоскости кадра.</p>`:check('deviceFrame','Корпус телефона',layer.deviceFrame)));
    if(real){
      specific+=section('Корпус и свет',`<div class="phone-colors">${PHONE_COLORS.map(([hex,name])=>`<button type="button" data-phone-color="${hex}" title="${name}" aria-label="${name}" aria-pressed="${layer.frameColor===hex}" style="--phone-color:${hex}"></button>`).join('')}</div>`+colors([['frameColor','Свой цвет',layer.frameColor]])+range('lightDirection','Направление света',layer.lightDirection,-180,180,1,'°')+range('lightIntensity','Яркость света',layer.lightIntensity,.25,2,.05)+range('reflection','Отражение на экране',layer.reflection,0,1,.05));
      specific+=section('Мои ракурсы',`<label class="field-label" for="saved-pose">Сохранённый ракурс</label><select id="saved-pose" ${poses.length?'':'disabled'}>${poses.length?poses.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join(''):'<option>Пока нет ракурсов</option>'}</select><div class="action-row" style="margin-top:10px"><button class="button" data-action="apply-pose" ${poses.length?'':'disabled'}>Применить</button><button class="button" data-action="save-pose" ${poses.length>=12?'disabled':''}>Сохранить</button><button class="button" data-action="delete-pose" ${poses.length?'':'disabled'} aria-label="Удалить ракурс">×</button></div>`);
      specific+=section('Экспорт мокапа',`<div class="export-row"><label for="export-scale">Масштаб мокапа</label><select id="export-scale">${[1,2,3].map(n=>`<option value="${n}" ${project.exportScale===n?'selected':''}>${n}×</option>`).join('')}</select></div><button class="button full" data-action="export-phone">PNG без фона</button><p class="small muted">Только выбранный телефон, с текущей тенью и ракурсом. Масштаб — ${project.exportScale}×.</p>`);
    }else specific+=section('Корпус',colors([['frameColor','Цвет',layer.frameColor]]));
  }else if(layer.type==='crop'){
    specific=section('Область интерфейса',`<button class="button full" data-action="edit-crop">Изменить область UI</button><p class="small muted" style="margin-top:9px">Вырезка связана с исходным экраном. После его замены проверь выбранную область.</p>`);
  }else{
    specific=section('Графика',`<img class="source-thumb" src="${esc(layer.image)}" alt="Графика выбранного слоя"><button class="button full" data-action="replace-graphic">Заменить изображение</button>`);
  }
  if(frame.columns===2&&['device','crop'].includes(layer.type))specific=section('Использовать экран кадра',select('sourceSide','Источник UI',layer.sourceSide??0,[[0,'Левый кадр'],[1,'Правый кадр']]))+specific;
  const geometry=section('Положение',`<div class="field-grid"><div>${field('x',frame.columns===2?'X, % ширины кадра':'X, % кадра',layer.x,-200,frame.columns===2?300:200,.1)}</div><div>${field('y','Y, % кадра',layer.y,-200,200,.1)}</div><div>${field('width','Ширина, %',layer.width,2,250,.1)}</div><div>${field('rotation','Поворот, °',layer.rotation,-180,180,1)}</div></div><div class="segmented" role="group" aria-label="Расположить слой"><button data-position="left" title="По левому полю">К левому краю</button><button data-position="center" title="По центру кадра">По центру</button><button data-position="right" title="По правому полю">К правому краю</button></div>`);
  const adaptation=section('Ресайз',select('resizeAnchor','Привязка по вертикали',layer.resizeAnchor??'auto',[['auto','Автоматически'],['top','К верху'],['center','К центру'],['bottom','К низу']])+`<p class="resize-note">${options.editScope==='format'?`Положение, размер и ракурс меняются только для ${project.format.replace('x',' × ')}.`:'Правки композиции применяются к обоим размерам.'} Привязка общая.</p>`+(Object.keys(layer.formatOverrides?.[project.format]??{}).length?'<button class="text-button" data-action="reset-layer-size">Вернуть авторесайз этого слоя</button>':''));
  const appearance=section('Вид',range('opacity','Непрозрачность',layer.opacity,0,1,.05)+(layer.type!=='text'?(isPhone3D(layer)?'':range('radius','Скругление',layer.radius,0,100,1))+range('shadow','Тень',layer.shadow,0,60,1):'')+(['crop','image'].includes(layer.type)?range('border','Обводка',layer.border,0,10,.5)+colors([['borderColor','Обводка',layer.borderColor]]):''));
  const index=frame.layers.findIndex(l=>l.id===layer.id);
  return `<div class="inspector-heading"><h2>${esc(layer.name)}</h2><button class="icon-button" data-action="deselect" aria-label="К оформлению кадра">×</button></div>${layer.locked?'<div class="lock-notice">Слой заблокирован. Разблокируй его, чтобы изменить.</div>':''}<div class="action-row" style="margin-bottom:18px"><button class="button" data-action="lock">${layer.locked?'Разблокировать':'Блокировать'}</button><button class="button" data-action="visibility">${layer.visible?'Скрыть':'Показать'}</button></div><fieldset ${layer.locked?'disabled':''}>${specific}${geometry}${adaptation}${appearance}${section('Слой',name+`<div class="action-row"><button class="button" data-action="up" ${index===frame.layers.length-1?'disabled':''}>Выше</button><button class="button" data-action="down" ${index===0?'disabled':''}>Ниже</button></div><div class="action-row"><button class="button" data-action="duplicate">Дублировать</button><button class="button" data-action="delete">Удалить</button></div>`)}</fieldset>`;
}
