import {marksFor,setMark,editMarks} from './text-marks.js';
import {VERSION,STORES,APPLE_FORMATS,formatFor,exportFormats,LOCALES,switchLocale,applyCopy,cloneProject,createProject,createSlide,validateProject,moveSlide,exportIssues,hasExamples,storeHint,slug} from './model.js';
import {ANDROID_DEVICES,IPHONE_DEVICES,deviceFor} from './devices.js';
import {createAIDialog} from './ai-dialog.js';
import {mountColorPicker} from './color-picker.js';
import {renderSlide,frameLayout,textColor,compositeColor} from './render.js';
import {loadImage,readScreenshot,suggestColors,saveBlob,pngBlob} from './media.js';
import {createRecoveryStore} from '../recovery-store.js';
import {createAutosave} from '../autosave.js';
import {createDemoImage} from '../demo.js';
import {makeZip} from '../zip.js';

const root=document.getElementById('app'),screensInput=document.getElementById('screens-input'),projectInput=document.getElementById('project-input');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={upload:'M12 16V3m-5 5 5-5 5 5M4 15v5h16v-5',arrow:'M5 12h14m-6-6 6 6-6 6',left:'m14 6-6 6 6 6',right:'m10 6 6 6-6 6',plus:'M12 5v14M5 12h14',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7',grip:'M8 5h.01M16 5h.01M8 12h.01M16 12h.01M8 19h.01M16 19h.01',undo:'M9 4 4 9l5 5M4 9h10a6 6 0 0 1 0 12',check:'m5 12 4 4L19 6'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.plus}"/></svg>`;
const labels=['Формат','Экраны','Оформление','Ваш комплект'];
const screenCount=n=>`${n} ${n===1?'экран':n>=2&&n<=4?'экрана':'экранов'}`;
const clone=cloneProject;
let project=createProject(),revision=0,step=1,images=new Map(),demo,history=[],busy=false,replaceId=null,dragId=null,noticeTimer,paintTicket=0,readyDownload=null,settingsCollapsed=true,activeText=null,focusText=false,panState=null,suppressClickUntil=0,samplingColor=null,activePhone=null,selectedSlideId=null,colorPicker=null;
const store=createRecoveryStore({name:'kadr-mvp-recovery:'+new URL('../',import.meta.url).pathname});
const autosave=createAutosave({store,validate:validateProject,getSnapshot:()=>({project,view:{step,wizardVersion:2}}),restore:async snapshot=>{
  const restored=validateProject(snapshot.project);await cacheImages(restored);project=restored;step=Math.max(1,Math.min(4,Number(snapshot.view?.step)||4));if(snapshot.view?.wizardVersion!==2&&Number(snapshot.view?.step)===4)step=3;
},onState:state=>{
  const el=document.getElementById('save-status');el.classList.toggle('error',['error','conflict'].includes(state.status));
  el.textContent=state.error||({loading:'Открываем проект…',idle:'Сохраняется в этом браузере',pending:'Сохраняем…',saving:'Сохраняем…',saved:'Сохранено в этом браузере'}[state.status]||'');
}});
function notice(message,error=false){const el=document.getElementById('notice');clearTimeout(noticeTimer);el.textContent=message;el.classList.toggle('error',error);el.hidden=false;noticeTimer=setTimeout(()=>el.hidden=true,error?10000:4500);}
function dialog(title,body,{confirm='Продолжить',cancel='Отмена',extra=''}={}){
  const el=document.getElementById('message-dialog');document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-body').textContent=body;document.getElementById('dialog-extra').innerHTML=extra;
  const yes=document.getElementById('dialog-confirm'),no=document.getElementById('dialog-cancel');yes.textContent=confirm;no.textContent=cancel;el.showModal();
  return new Promise(resolve=>{const finish=value=>{el.close();yes.onclick=no.onclick=el.oncancel=null;resolve(value);};yes.onclick=()=>finish(true);no.onclick=()=>finish(false);el.oncancel=e=>{e.preventDefault();finish(false);};});
}
function checkpoint(){history.push(clone(project));if(history.length>12)history.shift();}
function changed(action,{remember=true,rebuild=true}={}){if(remember)checkpoint();action();revision++;readyDownload=null;autosave.changed();if(rebuild)render();else{root.querySelector('.download-ready')?.remove();const undo=root.querySelector('[data-undo]');if(undo)undo.disabled=!history.length;schedulePaint();updateIssues();}}
async function cacheImages(p){const results=await Promise.all(p.slides.map(async s=>{const image=images.get(s.image)||await loadImage(s.image);if(image.naturalWidth!==s.width||image.naturalHeight!==s.height)throw new Error('Размеры изображения не совпадают с данными проекта.');return [s.image,image];}));for(const pair of results)images.set(...pair);}
function sampleSlide(index=0){return {id:'sample-'+index,image:demo?.src||'',width:414,height:896,title:index?'Всё важное\nпод рукой':'Меньше дел.\nБольше жизни.',subtitle:index?'Привычки и планы в одном месте':'Освободите время для себя'};}
function preview(){return `<aside class="preview-well"><div class="preview-meta"><span>${screenCount(project.slides.length)} · предпросмотр</span><span>${formatFor(project).workingWidth||1080} × ${formatFor(project).workingHeight||1920}</span></div><div class="preview-row pan-area" tabindex="0" aria-label="Предпросмотр всех слайдов, прокрутка по горизонтали">${project.slides.map((_,i)=>`<canvas data-preview="${i}" aria-label="Предпросмотр слайда ${i+1}"></canvas>`).join('')}</div><p class="preview-caption">Потяните холст влево или вправо, чтобы посмотреть весь комплект.</p></aside>`;}

function framesControl(){return `<div class="segmented" aria-label="Вид рамки">${[['device',STORES[project.store].phone],['outline','Обводка'],['none','Без рамки']].map(([id,name])=>`<button data-frame="${id}" aria-pressed="${project.frame===id}">${name}</button>`).join('')}</div>`;}
function deviceControl(){
 const locked=project.frame!=='device',apple=project.store==='apple',selected=apple?project.iphoneDevice:project.androidDevice||'android-generic';
 return `<div class="device-settings"><label class="field-label" for="device-select">Устройство</label><select id="device-select" data-device-select ${locked?'disabled':''}>${Object.entries(apple?IPHONE_DEVICES:ANDROID_DEVICES).filter(([id,d])=>!d.legacy||id===selected).map(([id,d])=>`<option value="${id}" ${id===selected?'selected':''}>${d.name}</option>`).join('')}</select><div class="device-color-row"><span>Цвет корпуса</span><button class="color-chip" data-open-color="device" ${locked?'disabled':''} aria-label="Цвет корпуса"><i style="background:${project.deviceColor||deviceFor(project).body}"></i><span>${project.deviceColor||'Оригинал'}</span></button><button class="reset-color" data-reset-device-color ${locked?'disabled':''} aria-label="Исходный цвет корпуса">↺</button></div></div>`;
}

function subtitleControl(){return `<label class="switch-label">Добавить подзаголовки<input type="checkbox" data-subtitle-toggle ${project.subtitleEnabled?'checked':''}></label>`;}
function cropControl(){return `<div class="crop-controls"><label>Масштаб телефона <output data-phone-output="phoneScale">${Math.round((project.phoneScale??1)*100)}%</output><input aria-label="Масштаб телефона" data-phone="phoneScale" type="range" min="60" max="180" value="${Math.round((project.phoneScale??1)*100)}"></label><label>Положение по вертикали <output data-phone-output="phoneY">${Math.round(project.phoneY*100)}%</output><input aria-label="Положение телефона" data-phone="phoneY" type="range" min="-20" max="30" value="${Math.round(project.phoneY*100)}"></label></div>`;}
function formatControl(){return project.store==='apple'?`<label class="field-label">Размер предпросмотра</label><div class="segmented">${Object.entries(APPLE_FORMATS).reverse().map(([id,f])=>`<button data-format="${id}" aria-pressed="${project.appleFormat===id}">${f.width} × ${f.height}</button>`).join('')}</div><p class="help">В ZIP попадут оба размера.</p>`:'';}
function platformOptions(){return Object.entries(STORES).map(([id,v])=>`<option value="${id}" ${id===project.store?'selected':''}>${id==='android'?'Android · 1080 × 1920':'App Store · два размера'}</option>`).join('');}
function colorChip(index){return `<button class="color-chip" data-open-color="${index}" aria-label="Цвет фона ${index+1}"><i style="background:${project.background.colors[index]}"></i><span data-color-value="${index}">${project.background.colors[index].toUpperCase()}</span></button>`;}
function displayedTextColor(){return project.textColor||textColor(project.background.colors.slice(0,project.background.mode==='solid'?1:2).map((c,i)=>compositeColor(c,project.background.opacities[i])));}
function colorValue(target,id){if(target==='device')return project.deviceColor||deviceFor(project).body;if(target==='text')return displayedTextColor();return project.background.colors[+target];}
function setColor(target,color,id){changed(()=>{if(target==='device')project.deviceColor=color;else if(target==='text')project.textColor=color;else project.background.colors[+target]=color;},{remember:false,rebuild:false});root.querySelectorAll(`[data-open-color="${target}"]`).forEach(button=>{button.querySelector('i')?.style.setProperty('background',color);const label=button.querySelector('span');if(label)label.textContent=color.toUpperCase();});const textChip=root.querySelector('[data-open-color="text"] i');if(textChip)textChip.style.background=displayedTextColor();}
function openColor(target,anchor){colorPicker?.close();document.getElementById('color-title').textContent='Цвет';checkpoint();const id=selectedSlide()?.id,allowOpacity=target==='text'||['0','1'].includes(target),opacity=target==='text'?project.textOpacity:project.background.opacities[+target];colorPicker=mountColorPicker({dialog:document.getElementById('color-dialog'),anchor,value:colorValue(target,id),opacity,allowOpacity,onOpacity:value=>changed(()=>{if(target==='text')project.textOpacity=value;else project.background.opacities[+target]=value;},{remember:false,rebuild:false}),onChange:color=>setColor(target,color,id),onSample:()=>{samplingColor={target,id};root.classList.add('sampling');notice('Нажмите на нужный цвет на любом кадре. Esc — отмена.');}});}

function selectedSlide(){return project.slides.find(s=>s.id===selectedSlideId)||project.slides[0];}
// Capture native selection before the nonmodal picker takes focus. Never recover
// it by searching for a phrase: repeated words must remain independent.
let selectionPointer=false,selectionKeyboard=false,selectionTimer,textEditCheckpoint=true,dismissedSelection=null;
function openSelectionColor(input){
 if(busy||!input?.isConnected||document.activeElement!==input||!input.hasAttribute('data-inline-input'))return;
 let start=input.selectionStart,end=input.selectionEnd;
 while(start<end&&/\s/.test(input.value[start]))start++;
 while(end>start&&/\s/.test(input.value[end-1]))end--;
 if(start===end){colorPicker?.close();return;}
 const id=input.dataset.id,field=input.dataset.text,source=input.value,locale=project.locale;
 const selectionKey=`${id}:${field}:${start}:${end}`;if(colorPicker?.selectionKey===selectionKey||dismissedSelection===selectionKey)return;
 colorPicker?.close();
 const slide=project.slides.find(s=>s.id===id);if(!slide)return;
 const previous=marksFor(slide,field).find(m=>m.start<=start&&m.end>=end);
 let style=previous?.style||'text',radius=previous?.radius??6,color=previous?.color||'#2563EB',remember=true;
 const valid=()=>project.locale===locale&&project.slides.find(s=>s.id===id)?.[field]===source;
 const apply=(reset=false)=>{if(!valid())return;changed(()=>{const s=project.slides.find(s=>s.id===id);s[field+'Marks']=setMark(marksFor(s,field),start,end,reset?null:{style,color,radius});s[field+'Highlight']='';},{remember,rebuild:false});remember=false;textEditCheckpoint=true;};
 const dialog=document.getElementById('color-dialog');document.getElementById('color-title').textContent='«'+source.slice(start,end)+'»';
 colorPicker=mountColorPicker({dialog,anchor:input,value:color,decoration:{style,radius},onChange:value=>{color=value;apply();},onDecoration:value=>{style=value.style;radius=value.radius;apply();},onReset:()=>apply(true),onSample:()=>{samplingColor={apply:value=>{color=value;apply();}};root.classList.add('sampling');notice('Нажмите на нужный цвет на кадре.');},onClose:()=>{dismissedSelection=selectionKey;colorPicker=null;}});
 colorPicker.selectionKey=selectionKey;
}
root.addEventListener('pointerdown',e=>{if(e.target.hasAttribute('data-inline-input')){selectionPointer=true;dismissedSelection=null;}});
window.addEventListener('pointerup',()=>{if(!selectionPointer)return;selectionPointer=false;const input=root.querySelector('[data-inline-input]');clearTimeout(selectionTimer);selectionTimer=setTimeout(()=>openSelectionColor(input),0);});
window.addEventListener('pointercancel',()=>selectionPointer=false);
root.addEventListener('keydown',e=>{if(e.target.hasAttribute('data-inline-input')&&e.shiftKey){selectionKeyboard=true;dismissedSelection=null;clearTimeout(selectionTimer);}});
root.addEventListener('keyup',e=>{if(e.key==='Shift')selectionKeyboard=false;if(!selectionKeyboard&&e.target.hasAttribute('data-inline-input')&&(e.key==='Shift'||e.key.startsWith('Arrow')||e.key==='a')){clearTimeout(selectionTimer);const input=e.target;selectionTimer=setTimeout(()=>openSelectionColor(input),0);}});
// Native touch selection handles can change a textarea selection without pointerup.
document.addEventListener('selectionchange',()=>{const input=document.activeElement;if(!selectionPointer&&!selectionKeyboard&&input?.hasAttribute('data-inline-input')){clearTimeout(selectionTimer);selectionTimer=setTimeout(()=>openSelectionColor(input),250);}});
function startInline(id,field){dismissedSelection=null;activePhone=null;selectedSlideId=id;activeText={id,field};focusText=true;render();root.querySelector(`[data-size-field="${field}"]`)?.scrollIntoView({block:'nearest'});}
function section(title,content){return `<section class="control-section"><h3>${title}</h3>${content}</section>`;}
function fontControl(field,all=false){const slide=selectedSlide(),size=slide?.[field+'Size']??(field==='title'?34:17),mixed=all&&project.slides.some(s=>s[field+'Size']!==size),label=field==='title'?'Размер заголовка':'Размер подзаголовка';return `<div class="size-row"><span>${field==='title'?'Заголовок':'Подзаголовок'}</span><span class="font-control"><button data-size-step="-1" data-size-field="${field}" ${all?'data-all':''} aria-label="Уменьшить: ${label}">−</button><input type="number" data-size-field="${field}" ${all?'data-all':''} aria-label="${label}" min="${field==='title'?18:12}" max="${field==='title'?56:28}" value="${mixed?'':size}" placeholder="Разные"><button data-size-step="1" data-size-field="${field}" ${all?'data-all':''} aria-label="Увеличить: ${label}">+</button></span></div>`;}
function typographyControl(){const s=selectedSlide();if(!s)return '';return `<label class="field-label" for="text-slide">Тексты слайда</label><select id="text-slide" data-text-slide>${project.slides.map((v,i)=>`<option value="${v.id}" ${v.id===s.id?'selected':''}>Слайд ${i+1}</option>`).join('')}</select>${['title',...(project.subtitleEnabled?['subtitle']:[])].map(field=>`<div class="text-settings">${fontControl(field)}<textarea data-panel-text data-text="${field}" data-id="${s.id}" data-focus-key="panel-${field}" aria-label="${field==='title'?'Заголовок':'Подзаголовок'} в панели" maxlength="${field==='title'?90:160}" rows="2">${esc(s[field])}</textarea></div>`).join('')}<button class="button small" data-apply-sizes>Применить размеры ко всем слайдам</button>`;}
function appearanceControls(){return section('Телефон',framesControl()+deviceControl()+cropControl())+section('Тексты',subtitleControl()+`<p class="control-hint">Размеры для всех слайдов</p>`+fontControl('title',true)+(project.subtitleEnabled?fontControl('subtitle',true):''))+section('Фон и цвет текста',backgroundControl());}

function backgroundControl(){return `<div class="segmented"><button data-bg-mode="solid" aria-pressed="${project.background.mode==='solid'}">Заливка</button><button data-bg-mode="gradient" aria-pressed="${project.background.mode==='gradient'}">Градиент</button></div><div class="color-stops">${colorChip(0)}${project.background.mode==='gradient'?colorChip(1):''}</div>${project.background.mode==='gradient'?`<label class="angle-control">Угол градиента <output data-angle-output>${project.background.angle??20}°</output><input aria-label="Угол градиента" data-angle type="range" min="0" max="360" value="${project.background.angle??20}"></label>`:''}<div class="device-color-row"><span>Текст</span><button class="color-chip" data-open-color="text" aria-label="Цвет текста"><i style="background:${displayedTextColor()}"></i><span>${project.textColor||'Авто'}</span></button><button class="reset-color" data-auto-text aria-label="Автоматический цвет текста">↺</button></div>`;}
function phoneToolbar(){const s=project.slides.find(s=>s.id===activePhone);if(!s){activePhone=null;return '';}return `<div class="text-toolbar phone-toolbar"><strong>Экран внутри телефона</strong><div class="segmented"><button data-screen-fit="cover" aria-pressed="${s.screenFit==='cover'}">Заполнить</button><button data-screen-fit="contain" aria-pressed="${s.screenFit==='contain'}">Вместить</button></div>${[['screenScale','Масштаб UI',100,300],['screenX','По горизонтали',-100,100],['screenY','По вертикали',-100,100]].map(([key,label,min,max])=>`<label>${label} <output data-screen-output="${key}">${Math.round(s[key]*100)}%</output><input type="range" data-screen="${key}" aria-label="${label}" min="${min}" max="${max}" value="${Math.round(s[key]*100)}"></label>`).join('')}<button class="button small" data-reset-screen>Сбросить</button><button class="button small" data-end-text>Готово</button></div>`;}

const ai=createAIDialog({getProject:()=>project,getRevision:()=>revision,getImage:key=>images.get(key),onApply:(locale,rows)=>{changed(()=>applyCopy(project,locale,rows));notice('Тексты применены. Язык можно переключить над холстом.');},onKeyChange:()=>{const b=root.querySelector('[data-ai]');if(b)b.textContent=ai.hasKey()?'GPT: тексты и перевод':'Подключить GPT';}});
function aiControls(){return `<div class="ai-toolbar"><label>Язык <select data-locale aria-label="Язык комплекта">${Object.entries(LOCALES).filter(([id])=>id==='source'||id===project.locale||project.slides.some(s=>s.copies[id])).map(([id,name])=>`<option value="${id}" ${project.locale===id?'selected':''}>${name}</option>`).join('')}</select></label><button class="button small" data-ai>${ai.hasKey()?'GPT: тексты и перевод':'Подключить GPT'}</button>${project.store==='apple'?`<label>Экспорт <select data-export-scale aria-label="Масштаб экспорта"><option value="3" ${project.exportScale===3?'selected':''}>3× · для App Store</option><option value="1" ${project.exportScale===1?'selected':''}>1× · рабочие размеры</option></select></label>`:''}<button class="button small add-screens" data-upload ${project.slides.length>=STORES[project.store].max?'disabled':''}>${icon('plus')}Добавить экраны</button></div>`;}
root.addEventListener('click',e=>{if(!busy&&e.target.closest('[data-ai]'))ai.open();});
root.addEventListener('change',e=>{if(busy)return;if(e.target.hasAttribute('data-locale'))changed(()=>{activeText=null;activePhone=null;switchLocale(project,e.target.value);});if(e.target.hasAttribute('data-export-scale'))changed(()=>project.exportScale=+e.target.value);});
function uploadControl(){return `<button class="dropzone" data-upload><span class="upload-icon">${icon('upload')}</span><strong>${project.slides.length?'Добавить ещё экраны':'Перетащите экраны или выберите файлы'}</strong><span>PNG, JPG, WebP · до ${STORES[project.store].max} экранов · до 20 МБ каждый</span></button>${project.slides.length?`<div class="upload-list">${project.slides.map((s,i)=>`<div class="upload-thumb"><img src="${s.image}" alt="Экран ${i+1}"><button data-remove="${s.id}" aria-label="Удалить экран ${i+1}">×</button></div>`).join('')}</div><p class="help">Загружено: ${project.slides.length}. Порядок можно изменить в редакторе.</p>`:''}`;}
function wizard(){
  let content='';
  if(step===1)content=`<p class="eyebrow">01 / Формат</p><h1>Где будет ваше приложение?</h1><p class="lead">Выберите платформу — размеры уже настроены.</p><div class="options platform-options"><button class="option" data-store="apple" aria-pressed="${project.store==='apple'}"><span class="store-logos"><img src="./assets/brands/app-store.png" alt="App Store"></span><span><span class="title">App Store</span><span class="description">iPhone · 440 × 956 и 414 × 896</span></span><span class="choice-check">✓</span></button><button class="option" data-store="android" aria-pressed="${project.store==='android'}"><span class="store-logos"><img src="./assets/brands/google-play.ico" alt="Google Play"></span><span><span class="title">Android</span><span class="description">RuStore и Google Play · 1080 × 1920</span></span><span class="choice-check">✓</span></button></div>`;
  if(step===2)content=`<p class="eyebrow">2. Исходные экраны</p><h1>Добавьте скриншоты</h1><p class="lead">Загрузите сразу весь комплект. Нужны вертикальные экраны приложения без внешней рамки телефона.</p>${uploadControl()}`;
  if(step===3)content=`<h1 class="compact-heading">Оформление</h1><div class="setup-controls">${appearanceControls()}</div>`;
  return `<ol class="stepper" aria-label="Этапы создания">${labels.map((name,i)=>`<li class="${i+1===step?'active':i+1<step?'done':''}" ${i+1===step?'aria-current="step"':''}><span class="step-num">${i+1<step?'✓':i+1}</span>${name}</li>`).join('')}</ol><div class="setup ${step<3?'setup-simple':''}"><section class="setup-content">${content}<div class="wizard-actions"><button class="button quiet" data-back ${step===1?'style="visibility:hidden"':''}>Назад</button><button class="button primary" data-next ${step===2&&!project.slides.length?'disabled':''}>${step===3?'Открыть редактор':'Далее'}${icon('arrow')}</button></div></section>${step>=3?preview():''}</div><div class="footnote">Изображения остаются в браузере до явного запуска GPT. Регистрация не нужна.</div>`;
}
function slideCard(s,i){const editing=activeText?.id===s.id?activeText.field:null;return `<article class="slide-card" data-slide="${s.id}"><div class="slide-head"><span class="slide-number" draggable="true" data-drag="${s.id}" title="Переставить слайд">${icon('grip')} ${String(i+1).padStart(2,'0')}</span><div class="slide-actions"><button data-move="${s.id}" data-direction="-1" aria-label="Слайд ${i+1} влево" ${i===0?'disabled':''}>${icon('left')}</button><button data-move="${s.id}" data-direction="1" aria-label="Слайд ${i+1} вправо" ${i===project.slides.length-1?'disabled':''}>${icon('right')}</button><button data-remove="${s.id}" aria-label="Удалить слайд ${i+1}">${icon('trash')}</button></div></div><div class="canvas-shell" style="aspect-ratio:${formatFor(project).width}/${formatFor(project).height}"><canvas class="slide-canvas" data-slide-canvas="${s.id}" aria-label="Слайд ${i+1}"></canvas><button class="phone-hit ${activePhone===s.id?'selected':''}" data-phone-hit="${s.id}" aria-label="Настроить экран внутри телефона на слайде ${i+1}"></button>${['title',...(project.subtitleEnabled?['subtitle']:[])].map(field=>editing===field?`<textarea class="inline-text" data-inline-input data-text="${field}" data-id="${s.id}" aria-label="${field==='title'?'Заголовок':'Подзаголовок'} слайда ${i+1}" maxlength="${field==='title'?90:160}" spellcheck="true">${esc(s[field])}</textarea>`:`<button class="text-hit" data-inline="${field}" data-id="${s.id}" aria-label="Редактировать ${field==='title'?'заголовок':'подзаголовок'} слайда ${i+1}">${s[field]?'':`<span>${field==='title'?'Добавить заголовок':'Добавить подзаголовок'}</span>`}</button>`).join('')}</div><div class="slide-footer"><button class="replace-screen" data-replace="${s.id}">Заменить экран</button>${(s.titleExample&&s.title)||(project.subtitleEnabled&&s.subtitleExample&&s.subtitle)?'<span class="example-tag">Текст-пример</span>':''}</div></article>`;}

function editor(){const spec=formatFor(project);return `<div class="editor"><div class="editor-heading"><div><input class="project-name" data-name aria-label="Название комплекта" maxlength="80" value="${esc(project.name)}"><p class="editor-subtitle">${project.store==='android'?'Android · RuStore / Google Play':'App Store'} · ${spec.workingWidth||spec.width} × ${spec.workingHeight||spec.height} · ${screenCount(project.slides.length)}</p></div><div class="export-actions"><button class="button" data-undo ${history.length?'':'disabled'}>${icon('undo')}Отменить</button><button class="button primary" data-export ${busy?'disabled':''}>${icon('download')}${busy?'Готовим PNG…':'Скачать комплект'}</button></div></div>${readyDownload?`<div class="download-ready"><p><strong>Комплект готов.</strong> ${readyDownload.count} PNG · ${readyDownload.description}</p><button class="button accent" data-download>Скачать ZIP</button></div>`:''}<div class="editor-grid"><aside class="settings ${settingsCollapsed?'collapsed':''}"><h2 class="settings-title">Оформление</h2><button class="settings-toggle mobile-only" data-toggle-settings>Оформление ${settingsCollapsed?'+':'−'}</button><div class="settings-content">${section('Тексты',typographyControl()+subtitleControl())}${activePhone?section('Экран внутри телефона',phoneToolbar()):''}${section('Платформа',`<select aria-label="Платформа" data-store-select>${platformOptions()}</select>`+formatControl())}${section('Телефон',framesControl()+deviceControl()+cropControl())}${section('Фон и цвет текста',backgroundControl())}</div></aside><section class="stage">${aiControls()}<div id="issues" class="issue" hidden></div><div class="filmstrip pan-area" tabindex="0" aria-label="Холст комплекта, прокрутка по горизонтали">${project.slides.map(slideCard).join('')}<button class="add-slide" data-upload ${project.slides.length>=spec.max?'disabled':''}>${icon('plus')}Добавить экран</button></div>${storeHint(project)?`<p class="store-hint">${storeHint(project)}</p>`:''}</section></div></div>`;}

function render(){clearTimeout(selectionTimer);colorPicker?.close();const panelFocus=document.activeElement?.dataset.focusKey,panelSelection=panelFocus?[document.activeElement.selectionStart,document.activeElement.selectionEnd]:null,settingsScroll=root.querySelector('.settings,.setup-content')?.scrollTop||0;root.style.setProperty('--card-ratio',formatFor(project).width/formatFor(project).height);const areas=[...root.querySelectorAll('.pan-area')].map(a=>[a.scrollLeft,a.scrollTop]);const wasEditing=document.activeElement?.hasAttribute('data-inline-input'),selection=wasEditing?[document.activeElement.selectionStart,document.activeElement.selectionEnd]:null;if(activePhone&&!project.slides.some(v=>v.id===activePhone))activePhone=null;if(activeText&&!project.slides.some(v=>v.id===activeText.id))activeText=null;root.innerHTML=step<4?wizard():editor();root.setAttribute('aria-busy',String(busy));root.inert=busy;document.body.classList.toggle('editing',step===4);document.getElementById('save-project').hidden=!project.slides.length;document.getElementById('new-project').hidden=!project.slides.length;for(const button of document.querySelectorAll('.header-actions button'))button.disabled=busy;[...root.querySelectorAll('.pan-area')].forEach((a,i)=>{a.scrollLeft=areas[i]?.[0]||0;a.scrollTop=areas[i]?.[1]||0;});const settings=root.querySelector('.settings,.setup-content');if(settings)settings.scrollTop=settingsScroll;if(panelFocus){const el=root.querySelector(`[data-focus-key="${panelFocus}"]`);el?.focus({preventScroll:true});if(panelSelection?.[0]!=null)el?.setSelectionRange(...panelSelection);}schedulePaint();updateIssues();if(focusText||(wasEditing&&activeText)){focusText=false;requestAnimationFrame(()=>{const el=root.querySelector('[data-inline-input]');el?.focus({preventScroll:true});if(selection)el?.setSelectionRange(...selection);});}}

function updateIssues(){const el=document.getElementById('issues');if(!el)return;const issues=exportIssues(project),ctx=document.createElement('canvas').getContext('2d');exportFormats(project).forEach(p=>p.slides.forEach((s,i)=>{if(frameLayout(ctx,p,s).overflow)issues.push(`Слайд ${i+1}: сократите текст, чтобы он читался и помещался (${formatFor(p).workingWidth||1080}).`);}));el.hidden=!issues.length;el.textContent=issues.join(' ');const button=root.querySelector('[data-export]');if(button)button.disabled=busy||issues.length>0;}
function schedulePaint(){const ticket=++paintTicket;requestAnimationFrame(()=>{if(ticket!==paintTicket)return;
 for(const canvas of root.querySelectorAll('[data-preview]')){const i=+canvas.dataset.preview,slide=project.slides[i];if(slide)renderSlide(canvas,project,slide,images.get(slide.image),i,{scale:.4});}
 for(const canvas of root.querySelectorAll('[data-layout-preview]')){const slide=project.slides[0]||sampleSlide(),p={...project,layout:canvas.dataset.layoutPreview,slides:[slide]};renderSlide(canvas,p,slide,images.get(slide.image)||demo,0,{scale:.13});}
 for(const canvas of root.querySelectorAll('[data-slide-canvas]')){const i=project.slides.findIndex(v=>v.id===canvas.dataset.slideCanvas),slide=project.slides[i];if(!slide)continue;const editing=activeText?.id===slide.id?activeText.field:null,l=renderSlide(canvas,project,slide,images.get(slide.image),i,{scale:.55});const shell=canvas.parentElement,factor=shell.clientWidth/l.w;const hit=shell.querySelector('[data-phone-hit]');if(hit)Object.assign(hit.style,{left:l.phone.x/l.w*100+'%',top:l.phone.y/l.h*100+'%',width:l.phone.width/l.w*100+'%',height:l.phone.height/l.h*100+'%'});
 for(const el of shell.querySelectorAll('[data-inline],[data-inline-input]')){const field=el.dataset.inline||el.dataset.text,heading=field==='title',text=heading?l.title:l.sub,lineHeight=heading?1.15:1.35,y=heading&&!slide.title?8:heading?l.titleY:l.subtitleY,margin=heading?32:36;Object.assign(el.style,{left:(margin/l.w*100)+'%',top:(y/l.h*100)+'%',width:((l.w-2*margin)/l.w*100)+'%',height:(Math.max(text.size*lineHeight,text.lines.length*text.size*lineHeight)+6)*factor+'px',fontSize:text.size*factor+'px',fontWeight:heading?'700':'400',lineHeight:String(lineHeight),opacity:String((heading?1:.8)*project.textOpacity),color:displayedTextColor(),caretColor:displayedTextColor()});}
 }
});}

async function addFiles(files){
  if(busy)return;const list=[...files];if(!list.length)return;
  const available=replaceId?1:Math.max(0,STORES[project.store].max-project.slides.length);
  if(list.length>available){notice(replaceId?'Для замены выберите один экран.':`Можно добавить ещё ${available} экранов. Выберите меньше файлов.`,true);replaceId=null;return;}
  busy=true;const target=replaceId;replaceId=null;render();notice('Загружаем экраны…');
  try{
    const uploaded=[];for(const file of list){const media=await readScreenshot(file);uploaded.push({...media,name:file.name});}
    const next=clone(project);
    if(target){const s=next.slides.find(s=>s.id===target);if(!s)throw new Error('Слайд уже удалён.');Object.assign(s,{image:uploaded[0].source,name:uploaded[0].name,width:uploaded[0].width,height:uploaded[0].height});}
    else for(const m of uploaded)next.slides.push(createSlide(m.source,m.name,m.width,m.height,next.slides.length));
    validateProject(next);for(const m of uploaded)images.set(m.source,m.image);
    changed(()=>project=next);notice(target?'Экран заменён. Тексты и оформление сохранены.':`Добавлено экранов: ${uploaded.length}.`);
  }catch(error){notice(error.message,true);}finally{busy=false;screensInput.value='';render();}
}
function chooseScreens(id=null){if(busy)return;replaceId=id;screensInput.multiple=!id;screensInput.click();}
async function exportPack(){
  if(busy||exportIssues(project).length)return;
  if(hasExamples(project)&&!await dialog('В комплекте остались тексты-примеры','Их можно заменить прямо на кадрах. Скачать изображения с этими текстами?',{confirm:'Скачать как есть',cancel:'Изменить тексты'}))return;
  activeText=null;
  const ctx=document.createElement('canvas').getContext('2d');if(exportFormats(project).some(p=>p.slides.some(s=>frameLayout(ctx,p,s).overflow))){notice('Сократите длинные заголовки перед экспортом.',true);return;}
  busy=true;readyDownload=null;render();const snapshot=clone(project),files=[];
  try{
    await cacheImages(snapshot);
    const formats=exportFormats(snapshot);for(const variant of formats)for(let i=0;i<snapshot.slides.length;i++){
      const canvas=document.createElement('canvas');renderSlide(canvas,variant,snapshot.slides[i],images.get(snapshot.slides[i].image),i,{scale:snapshot.store==='apple'?snapshot.exportScale/3:1});
      const blob=await pngBlob(canvas);files.push({name:`${snapshot.locale}/${snapshot.store==='apple'?APPLE_FORMATS[variant.appleFormat].width*snapshot.exportScale+'x'+APPLE_FORMATS[variant.appleFormat].height*snapshot.exportScale:'1080x1920'}/${String(i+1).padStart(2,'0')}.png`,data:new Uint8Array(await blob.arrayBuffer())});canvas.width=canvas.height=1;
      const button=root.querySelector('[data-export]');if(button)button.textContent=`Готовим ${i+1} из ${snapshot.slides.length}…`;
      await new Promise(resolve=>setTimeout(resolve,0));
    }
    readyDownload={count:files.length,description:snapshot.store==='apple'?(snapshot.exportScale===3?'1320 × 2868 и 1242 × 2688':'440 × 956 и 414 × 896'):'1080 × 1920',blob:makeZip(files),name:`${slug(snapshot.name)}-${snapshot.store}-${snapshot.locale}.zip`};saveBlob(readyDownload.blob,readyDownload.name);notice('Комплект готов. PNG собраны в один ZIP.');
  }catch(error){notice(error.message||'Не удалось подготовить комплект. Попробуйте снова.',true);}finally{busy=false;render();}
}
root.addEventListener('click',e=>{const el=e.target.closest('button');if(!el||busy)return;if(el.hasAttribute('data-phone-hit')){if(Date.now()<suppressClickUntil)return;activeText=null;activePhone=el.dataset.phoneHit;selectedSlideId=activePhone;render();root.querySelector('.phone-toolbar')?.scrollIntoView({block:'nearest'});}
 if(el.hasAttribute('data-format'))changed(()=>project.appleFormat=el.dataset.format);
 if(el.hasAttribute('data-auto-text'))changed(()=>{project.textColor=null;project.textOpacity=1;});
 if(el.hasAttribute('data-screen-fit')&&activePhone)changed(()=>project.slides.find(s=>s.id===activePhone).screenFit=el.dataset.screenFit);
 if(el.hasAttribute('data-reset-screen')&&activePhone)changed(()=>Object.assign(project.slides.find(s=>s.id===activePhone),{screenFit:'cover',screenScale:1,screenX:0,screenY:0}));
});
root.addEventListener('input',e=>{if(busy)return;const el=e.target;if(el.hasAttribute('data-screen')&&activePhone){changed(()=>project.slides.find(s=>s.id===activePhone)[el.dataset.screen]=+el.value/100,{remember:false,rebuild:false});root.querySelector(`[data-screen-output="${el.dataset.screen}"]`).textContent=el.value+'%';}});
root.addEventListener('click',async event=>{
  const el=event.target.closest('button');if(!el||busy||(Date.now()<suppressClickUntil&&el.closest('.pan-area')))return;
  if(el.hasAttribute('data-inline'))return startInline(el.dataset.id,el.dataset.inline);
  if(el.hasAttribute('data-end-text')){activeText=null;activePhone=null;render();return;}
  if(el.hasAttribute('data-open-color'))return openColor(el.dataset.openColor,el);
  if(el.hasAttribute('data-reset-device-color'))return changed(()=>project.deviceColor=null);
  if(el.hasAttribute('data-bg-mode'))return changed(()=>project.background.mode=el.dataset.bgMode);
  if(el.hasAttribute('data-store'))return changed(()=>project.store=el.dataset.store);
  if(el.hasAttribute('data-frame'))return changed(()=>project.frame=el.dataset.frame);
  if(el.hasAttribute('data-layout'))return changed(()=>project.layout=el.dataset.layout);

  if(el.hasAttribute('data-next')){if(step===2&&!project.slides.length)return;step=Math.min(4,step+1);autosave.changed();render();window.scrollTo({top:0});return;}
  if(el.hasAttribute('data-back')){step=Math.max(1,step-1);autosave.changed();render();return;}
  if(el.hasAttribute('data-upload'))return chooseScreens();
  if(el.hasAttribute('data-replace'))return chooseScreens(el.dataset.replace);
  if(el.hasAttribute('data-remove')){const s=project.slides.find(s=>s.id===el.dataset.remove);if(!s)return;if((s.title||s.subtitle)&&!await dialog('Удалить слайд?','Экран и его тексты будут удалены из комплекта. Действие можно отменить.',{confirm:'Удалить'}))return;return changed(()=>{project.slides=project.slides.filter(s=>s.id!==el.dataset.remove);});}
  if(el.hasAttribute('data-move'))return changed(()=>{const i=project.slides.findIndex(s=>s.id===el.dataset.move);moveSlide(project,i,i+Number(el.dataset.direction));});
  if(el.hasAttribute('data-auto-color')){const first=project.slides[0];if(!first)return;const colors=suggestColors(images.get(first.image));if(!colors)return notice('На экране нет выраженного акцентного цвета. Выберите готовый фон.');changed(()=>{project.background={mode:'gradient',angle:project.background.angle??20,colors};});return notice('Фон подобран из цвета первого экрана.');}
  if(el.hasAttribute('data-undo')){const previous=history.pop();if(previous)changed(()=>project=previous,{remember:false});return;}
  if(el.hasAttribute('data-export'))return exportPack();
  if(el.hasAttribute('data-download')&&readyDownload)return saveBlob(readyDownload.blob,readyDownload.name);
  if(el.hasAttribute('data-toggle-settings')){settingsCollapsed=!settingsCollapsed;render();return;}
  if(el.hasAttribute('data-slide-canvas'))document.getElementById('title-'+el.dataset.slideCanvas)?.focus();
});
root.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)&&event.target.hasAttribute('data-slide-canvas')){event.preventDefault();event.target.click();}});
root.addEventListener('focusin',event=>{if(event.target.matches('[data-text]'))textEditCheckpoint=true;if(event.target.matches('[data-name],[data-phone],[data-screen],[data-angle],[data-size-field]'))checkpoint();if(activeText&&event.target.matches('[data-panel-text]')){activeText=null;render();}});
function sizeTargets(el){return el.hasAttribute('data-all')?project.slides:[selectedSlide()].filter(Boolean);}
root.addEventListener('input',e=>{const el=e.target;if(busy)return;if(el.hasAttribute('data-size-field')&&el.value!==''&&el.validity.valid)changed(()=>sizeTargets(el).forEach(s=>s[el.dataset.sizeField+'Size']=+el.value),{remember:false,rebuild:false});});
root.addEventListener('click',e=>{const el=e.target.closest('button');if(!el||busy)return;if(el.hasAttribute('data-size-step')){const field=el.dataset.sizeField;changed(()=>sizeTargets(el).forEach(s=>s[field+'Size']=Math.max(field==='title'?18:12,Math.min(field==='title'?56:28,s[field+'Size']+Number(el.dataset.sizeStep)))));}if(el.hasAttribute('data-apply-sizes')){const current=selectedSlide();if(current)changed(()=>project.slides.forEach(s=>{s.titleSize=current.titleSize;s.subtitleSize=current.subtitleSize;}));notice('Размеры текста применены ко всем слайдам.');}});
root.addEventListener('change',e=>{if(e.target.hasAttribute('data-text-slide')){selectedSlideId=e.target.value;activeText=null;activePhone=null;render();root.querySelector(`[data-slide="${selectedSlideId}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});}});
root.addEventListener('input',event=>{
  if(busy)return;const el=event.target;
  if(el.hasAttribute('data-text')){colorPicker?.close();root.querySelectorAll(`[data-text="${el.dataset.text}"][data-id="${el.dataset.id}"]`).forEach(other=>{if(other!==el)other.value=el.value;});const s=project.slides.find(s=>s.id===el.dataset.id);if(!s)return;changed(()=>{const field=el.dataset.text;s[field+'Marks']=editMarks(marksFor(s,field),s[field],el.value);s[field+'Highlight']='';s[field]=el.value;s[field+'Example']=false;},{remember:textEditCheckpoint,rebuild:false});textEditCheckpoint=false;if(!((s.titleExample&&s.title)||(project.subtitleEnabled&&s.subtitleExample&&s.subtitle)))el.closest('.slide-card')?.querySelector('.example-tag')?.remove();const count=root.querySelector(`[data-count="${s.id}-${el.dataset.text}"]`);if(count)count.textContent=`${el.value.length}/${el.dataset.text==='title'?90:160}`;}
  if(el.hasAttribute('data-name'))changed(()=>project.name=el.value,{remember:false,rebuild:false});
  if(el.hasAttribute('data-phone')){changed(()=>{if(project.phoneScale==null)project.phoneScale=1;project[el.dataset.phone]=Number(el.value)/100;},{remember:false,rebuild:false});root.querySelector(`[data-phone-output="${el.dataset.phone}"]`).textContent=el.value+'%';}
  if(el.hasAttribute('data-angle')){changed(()=>project.background.angle=Number(el.value),{remember:false,rebuild:false});root.querySelector('[data-angle-output]').textContent=el.value+'°';}
  if(el.hasAttribute('data-color'))changed(()=>project.background.colors[+el.dataset.color]=el.value,{remember:false,rebuild:false});
});
root.addEventListener('change',event=>{if(busy)return;const el=event.target;if(el.hasAttribute('data-subtitle-toggle'))changed(()=>project.subtitleEnabled=el.checked);if(el.hasAttribute('data-gradient'))changed(()=>project.background.mode=el.checked?'gradient':'solid');if(el.hasAttribute('data-store-select'))changed(()=>project.store=el.value);if(el.hasAttribute('data-device-select')&&Object.hasOwn(project.store==='apple'?IPHONE_DEVICES:ANDROID_DEVICES,el.value))changed(()=>project[project.store==='apple'?'iphoneDevice':'androidDevice']=el.value);});
root.addEventListener('dragstart',event=>{const el=event.target.closest('[data-drag]');if(!el||busy)return;dragId=el.dataset.drag;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',dragId);el.closest('.slide-card')?.classList.add('dragging');});
root.addEventListener('dragover',event=>{if(event.dataTransfer.types.includes('Files')){event.preventDefault();root.querySelector('.dropzone')?.classList.add('dragover');return;}if(dragId&&event.target.closest('.slide-card')){event.preventDefault();event.dataTransfer.dropEffect='move';root.querySelectorAll('.drag-target').forEach(e=>e.classList.remove('drag-target'));event.target.closest('.slide-card').classList.add('drag-target');}});
root.addEventListener('drop',event=>{event.preventDefault();if(event.dataTransfer.files.length){replaceId=null;addFiles(event.dataTransfer.files);return;}const target=event.target.closest('.slide-card')?.dataset.slide;if(dragId&&target){const from=project.slides.findIndex(s=>s.id===dragId),to=project.slides.findIndex(s=>s.id===target);if(from!==to)changed(()=>moveSlide(project,from,to));}dragId=null;});
root.addEventListener('dragend',()=>{dragId=null;root.querySelectorAll('.dragging,.drag-target,.dragover').forEach(e=>e.classList.remove('dragging','drag-target','dragover'));});
screensInput.addEventListener('change',()=>addFiles(screensInput.files));
document.getElementById('open-project').addEventListener('click',()=>{if(!busy)projectInput.click();});
document.getElementById('save-project').addEventListener('click',()=>{try{saveBlob(new Blob([JSON.stringify(validateProject(project))],{type:'application/json'}),slug(project.name)+'.kadr.json');notice('Проект сохранён в файл вместе с изображениями.');}catch(error){notice(error.message,true);}});
projectInput.addEventListener('change',async()=>{
  const file=projectInput.files[0];projectInput.value='';if(!file||busy)return;
  try{
    if(file.size>190*1024*1024)throw new Error('Файл больше 190 МБ.');
    const next=validateProject(JSON.parse(await file.text()));await cacheImages(next);
    if(project.slides.length&&!await dialog('Открыть другой проект?','Текущий комплект будет заменён. Если он нужен, сначала сохраните его в файл.',{confirm:'Открыть'}))return;
    changed(()=>{project=next;step=4;});notice('Проект открыт.');
  }catch(error){if(error.name==='LegacyProjectError')await dialog('Проект предыдущей версии',error.message,{confirm:'Понятно',cancel:'Закрыть',extra:'<a href="./legacy.html" target="_blank" rel="noopener">Открыть предыдущий редактор</a>'});else notice(error instanceof SyntaxError?'Не удалось прочитать файл проекта.':error.message,true);}
});
document.getElementById('new-project').addEventListener('click',async()=>{if(busy)return;if(!await dialog('Начать новый комплект?','Текущий комплект останется в скачанном файле, если вы его сохранили. Новый комплект заменит локальное автосохранение.',{confirm:'Начать заново'}))return;changed(()=>{project=createProject();step=1;activeText=null;});notice('Можно создавать новый комплект.');});
window.addEventListener('beforeunload',event=>{if(autosave.hasUnsaved()){event.preventDefault();event.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')autosave.flush();});

root.addEventListener('pointerdown',event=>{
 const area=event.target.closest('.pan-area');if(!area||busy)return;
 if(samplingColor!==null){const canvas=event.target.closest('.canvas-shell')?.querySelector('canvas')||event.target.closest('canvas');if(canvas){const r=canvas.getBoundingClientRect(),x=Math.max(0,Math.min(canvas.width-1,Math.floor((event.clientX-r.left)*canvas.width/r.width))),y=Math.max(0,Math.min(canvas.height-1,Math.floor((event.clientY-r.top)*canvas.height/r.height))),rgb=canvas.getContext('2d').getImageData(x,y,1,1).data,color='#'+[...rgb].slice(0,3).map(v=>v.toString(16).padStart(2,'0')).join('');if(samplingColor.apply)samplingColor.apply(color);else setColor(samplingColor.target,color,samplingColor.id);samplingColor=null;root.classList.remove('sampling');suppressClickUntil=Date.now()+350;render();notice('Цвет выбран.');}event.preventDefault();return;}
 if(event.pointerType!=='mouse'||event.button!==0||event.target.closest('input,textarea,select,[data-drag],button:not([data-inline]):not([data-phone-hit])'))return;
 panState={area,x:event.clientX,y:event.clientY,left:area.scrollLeft,top:area.scrollTop,target:event.target.closest('[data-inline],[data-phone-hit]'),moved:false,id:event.pointerId};
});
root.addEventListener('pointermove',event=>{if(!panState||event.pointerId!==panState.id)return;const dx=event.clientX-panState.x,dy=event.clientY-panState.y;if(Math.abs(dx)+Math.abs(dy)>5&&!panState.moved){panState.moved=true;panState.area.setPointerCapture(event.pointerId);panState.area.classList.add('panning');}if(panState.moved){event.preventDefault();panState.area.scrollLeft=panState.left-dx;panState.area.scrollTop=panState.top-dy;}});
function endPan(){if(panState?.moved){suppressClickUntil=Date.now()+350;panState.area.classList.remove('panning');if(panState.area.hasPointerCapture(panState.id))panState.area.releasePointerCapture(panState.id);}panState=null;}
root.addEventListener('pointerup',endPan);root.addEventListener('pointercancel',endPan);window.addEventListener('pointerup',endPan);
window.addEventListener('resize',schedulePaint);
window.addEventListener('keydown',event=>{if(event.key==='Escape'&&!event.defaultPrevented){samplingColor=null;root.classList.remove('sampling');if(activeText||activePhone){activeText=null;activePhone=null;render();}}});

try{demo=await loadImage(createDemoImage());await autosave.start();render();}catch(error){root.textContent='Не удалось открыть редактор. Обновите страницу.';notice(error.message,true);}
